inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/controllers/software_records_controller_spec.rb'
    - 'spec/controllers/front_controller_spec.rb'
Metrics/MethodLength:
  Exclude:
    - 'load_records.rb'
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Lint/UselessAssignment:
  Exclude:
    - 'app/helpers/software_records_helper.rb'
