# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe HostingEnvironmentsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # HostingEnvironment. As you add validations to HostingEnvironment, be sure to
  # adjust the attributes here as well.
  include Devise::Test::ControllerHelpers
  render_views

  let(:valid_attributes) do
    {
      title: 'Test',
      description: 'Test Hosting env.'
    }
  end

  let(:invalid_attributes) do
    {
      title: ''
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HostingEnvironmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  def sign_in_user(admin)
    sign_in admin
  end

  before do
    admin = FactoryBot.create(:admin)
    sign_in_user(admin)
  end

  describe 'GET #index' do
    it 'returns a success response' do
      HostingEnvironment.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      hosting_environment = HostingEnvironment.create! valid_attributes
      get :show, params: { id: hosting_environment.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      hosting_environment = HostingEnvironment.create! valid_attributes
      get :edit, params: { id: hosting_environment.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new HostingEnvironment' do
        expect do
          post :create, params: { hosting_environment: valid_attributes }, session: valid_session
        end.to change(HostingEnvironment, :count).by(1)
      end

      it 'redirects to the created hosting_environment' do
        post :create, params: { hosting_environment: valid_attributes }, session: valid_session
        expect(response).to redirect_to(HostingEnvironment.last)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { hosting_environment: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        { title: 'Test New Env.', description: 'new hosting environment' }
      end

      it 'updates the requested hosting_environment' do
        hosting_environment = HostingEnvironment.create! valid_attributes
        put :update,
            params: { id: hosting_environment.to_param, hosting_environment: new_attributes }, session: valid_session
        hosting_environment.reload
        expect(hosting_environment.title).to eq('Test New Env.')
        expect(hosting_environment.description).to eq('new hosting environment')
      end

      it 'redirects to the hosting_environment' do
        hosting_environment = HostingEnvironment.create! valid_attributes
        put :update,
            params: { id: hosting_environment.to_param, hosting_environment: valid_attributes }, session: valid_session
        expect(response).to redirect_to(hosting_environment)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        hosting_environment = HostingEnvironment.create! valid_attributes
        put :update,
            params: { id: hosting_environment.to_param, hosting_environment: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested hosting_environment' do
      hosting_environment = HostingEnvironment.create! valid_attributes
      expect do
        delete :destroy, params: { id: hosting_environment.to_param }, session: valid_session
      end.to change(HostingEnvironment, :count).by(-1)
    end

    it 'redirects to the hosting_environments list' do
      hosting_environment = HostingEnvironment.create! valid_attributes
      delete :destroy, params: { id: hosting_environment.to_param }, session: valid_session
      expect(response).to redirect_to(hosting_environments_url)
    end
  end
end
