name: CI GitHub Action
on: "push"

#permissions:
#  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run rubocop
      run: |
        bundle exec rubocop
    - name: Run tests
      run: bundle exec rake
    - name: Coveralls
      uses: coverallsapp/github-action@v2
    - name: Bundler Audit Action
      uses: andrewmcodes/bundler-audit-action@v0.1.0
    - name: Brakeman linter
      run: bundle exec brakeman --no-exit-on-warn --no-exit-on-error
